{
  "cameras": [
    {
      "serial": "DA6135210",
      "fps": 30,
      "put_desired_frequency": 30,
      # "input_res": [480, 480],
      # "output_res": [384, 384],
    },
    {
      "serial": "DA6022596",
      "fps": 30,
      "put_desired_frequency": 30,
      # "input_res": [480, 480],
      # "output_res": [384, 384],
    }
  ],
  # robot configurations, 0->right 1->left
  # comment out robot #1 if only using 1 arm
  "robots": [
    {
      "robot_type": "ur5e",
      "robot_ip": "192.168.56.20",
      "robot_obs_latency": 0.0001, "robot_action_latency": 0.167, "tcp_offset": 0.3,  # 0.295 for zhixing gripper
      # table height for finger-table collision avoidance
      # -inf to disable
      "height_threshold": -0.1, 
      # sphere collision primitive size and location for inter-gripper collision avoidance
      # 0 to disable
      "sphere_radius": 0.1, "sphere_center": [0, -0.06, -0.185],
      "unified_tx": [
        [ 0.70710678,  0.70710678,  0.        ,  0.        ],
        [-0.70710678,  0.70710678,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  1.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  1.        ]
      ],
    },
    {
      "robot_type": "ur5e",
      "robot_ip": "192.168.56.10",
      "robot_obs_latency": 0.0001, "robot_action_latency": 0.167, "tcp_offset": 0.3,
      "height_threshold": -0.1,
      "sphere_radius": 0.1, "sphere_center": [0, -0.06, -0.185],
      "unified_tx": [
        [-0.70710678,  0.70710678,  0.        ,  0.        ],
        [-0.70710678, -0.70710678,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  1.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  1.        ]
      ],
    }
  ],
  # gripper configurations, 0->right 1->left
   "grippers": [
    {
      "gripper_type": "zhixing",
      "serial": "4294935675",
      "gripper_obs_latency": 0.0157, "gripper_action_latency": 0,
      "force": 30,
      "open_width": 0.12, "closed_width": 0.0, "finger_thickness": 0.023
    },
    {
      "gripper_type": "zhixing",
      "serial": "1638440",
      "gripper_obs_latency": 0.0157, "gripper_action_latency": 0,
      "force": 30,
      "open_width": 0.12, "closed_width": 0.0, "finger_thickness": 0.023
    }
  ],
  "tx_left_right": [
    [ 1.        ,  0.        ,  0.        ,  0.01      ],
    [ 0.        ,  1.        ,  0.        , -0.927     ],
    [ 0.        ,  0.        ,  1.        , -0.01     ],
    [ 0.        ,  0.        ,  0.        ,  1.        ]
  ],
  "tx_tracker_to_tcp": [
    [ 1.        ,  0.        ,  0.        ,  0.        ],
    [ 0.        ,  1.        ,  0.        ,  0.070261  ],
    [ 0.        ,  0.        ,  1.        ,  0.272602  ],
    [ 0.        ,  0.        ,  0.        ,  1.        ]
  ]
}
